### ISSUE TITLE
jetson-stats not supported for [L4T 32.5.2]

### ISSUE THREAD

**Issue by moran991231** [rbonghi/jetson_stats#190] opened 2022-01-13 12:12 UTC
***Logout and reboot didn't work to me!***
**`sudo systemctl restart jetson_stats.service ` also didn't work** 

Please update jetson-stats with new jetpack

**Linux for Tegra**
 - L4T: 32.5.2

**Jetson-Stats**
 - Version: 3.1.1
 
![asdf](https://user-images.githubusercontent.com/55349869/149328209-b4007254-251d-4654-887d-b38c24908150.png)

**Comment by moran991231** [comment] 2022-01-13 12:16
Plz help me

**Comment by clintlombard** [comment] 2022-01-13 13:27
I get the same warning, but everything seems to work fine in `jtop`

**Comment by clintlombard** [comment] 2022-01-13 13:28
Duplicate of #185

**Comment by rbonghi** [comment] 2022-01-13 13:37
I read now. I fix soon :-)

**Closed** 2022-01-13 17:01 UTC
Labels: missing

**Comment by rbonghi** [comment] 2022-01-13 18:13
Please update jetson-stats to **3.1.2**

```
sudo -H pip install -U jetson-stats
```

and reboot your board

**Comment by moran991231** [comment] 2022-01-14 00:18
It worked! Thanks!!! :)

**Comment by moran991231** [comment] 2022-01-14 01:45
Hi I have a question.
I have an account that I made at first when installing jetpack --> let this account `user0`  
And then, I made another one after installation jetpack --> let this `user`

With `user0` I can run `jtop` successfully.  
However with `user1`, `jtop` doesn't work, even though I try it after rebooting.
```bash
user1@my_board:~$ jtop
I can't access jetson_stats.service.
Please logout or reboot this board.
```
Fortunately, I can run through `sudo jtop` with `user1` (I can see a warning comment)
```bash
user1@my_board:~$ sudo jtop
[sudo] password for user1: 
[WARN] SUDO is no more required
```
Anyway I can run jtop with user1, but I wonder why it doesn't work through `jtop`.
I think you can give me a advice.
Thanks for reading

**Comment by rbonghi** [comment] 2022-01-14 11:31
because the second user is not in the same group and doesn't have access without sudo.

To enable it:
```
usermod -a -G jetson_stats user1
```
**remember to logout and login**
